### ISSUE TITLE
Fatal error on Android when scheduled notification time is reached

### ISSUE THREAD

**Issue by kirkryan** [wumke/react-native-local-notifications#29]
The package is working great on iOS for us, however, there is a problem with Android whereby it causes a fatal exception and crashes the app.

This is the output of LogCat at the time of the exception
```
2019-07-09 13:10:00.926 28607-28607/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.busbynative:remote, PID: 28607
    java.lang.RuntimeException: Unable to start receiver com.github.wumke.RNLocalNotifications.AlarmReceiver: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=null vibrate=[0,1000] sound=content://settings/system/notification_sound defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3039)
        at android.app.ActivityThread.-wrap18(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=null vibrate=[0,1000] sound=content://settings/system/notification_sound defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:306)
        at android.app.NotificationManager.notify(NotificationManager.java:284)
        at android.app.NotificationManager.notify(NotificationManager.java:268)
        at com.github.wumke.RNLocalNotifications.AlarmReceiver.onReceive(AlarmReceiver.java:131)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap18(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
```

We are invoking the notification with the following:

```
// Manual test notification
    RNLocalNotifications.createNotification(
      1,
      "Incident notification",
      "2019-07-09 13:10",
      "busby"
    );
```

We are using react-native 0.59.10 and have followed all of the installation instructions to the letter. Any ideas on this one?

**Comment by wumke** [comment]
Is it possible that you missed the following:
> Aside from the big icon, for which the ic_launcher icon in mipmap folder is used by default, you also need a small transparent with white foreground icon which will be displayed in the status bar. See Android developer specifications for correct sizes, by default 'notification_small' from the drawable folder is used...

Since you get an error 'Invalid notification (no valid small icon)' that seems the problem to me. Did you add the notification icons?

**Comment by kirkryan** [comment]
Hi @wumke 

That's fixed it! Thanks for the prompt response! 

We added our image directly to the drawable folder:

![image](https://user-images.githubusercontent.com/18603029/60888018-b6871b80-a24d-11e9-8fea-3763d4f6e09b.png)

One thing we did notice is that the message is not shown (it's hidden until unlocked), it there a way of showing the message even if the phone is locked?

We alert in real-time, so will raising an alert with the current time work or is there a way of specifying seconds so that we could, for example, add 3 seconds to the scheduled time?

**Comment by wumke** [comment]
Phone locked state notification handling is up to the os and its settings ( there is an app out there in the store that turns screen on and sisplays notification like iphones do, but I forgot the name... only remember that it has a minor issue that stopped the sound to early sometimes :p )

If you want to alert in real time, why don't you use push notifications then? Local notifications are great for scheduling later in time and work completely offline... (That aside, I don't know anymore if it ignores or immediately displays the notification at the exact current time, just give it a try and see what happens)

**Comment by kirkryan** [comment]
Thanks for your help @wumke
